<Project>
  <!-- User properties -->
  <PropertyGroup>
    <!-- Путь к папке с игрой PEAK -->
    <PEAKGameRootDir>D:\SteamLibrary\steamapps\common\PEAK</PEAKGameRootDir>

    <!-- Путь к папке BepInEx (обычно внутри GameDir) -->
    <PEAKBepInExDir>$(PEAKGameRootDir)\BepInEx</PEAKBepInExDir>

    <!-- Включить автоматическое копирование мода в папку plugins -->
    <DeployModFiles>true</DeployModFiles>
  </PropertyGroup>
</Project>